import type { ExamData, ExamId } from "../types";
import metaJson from "../data/meta.json";

export interface ExamMeta {
  examId: ExamId;
  examName: string;
  examShort: string;
  questionCount: number;
}

// meta.json is regenerated by scripts/parse-questions.mjs alongside the per-exam
// question files. It's small enough to ship in the main bundle so the setup
// screen can show counts without pulling the full question arrays.
export const examMeta: Record<ExamId, ExamMeta> = metaJson as Record<ExamId, ExamMeta>;

export const examMetaList: ExamMeta[] = [
  examMeta["ai-practitioner"],
  examMeta["cloud-practitioner"],
];

// Lazy-loaded — Vite splits each JSON into its own chunk so users only download
// the question set they actually start.
export async function loadExam(id: ExamId): Promise<ExamData> {
  switch (id) {
    case "cloud-practitioner": {
      const m = await import("../data/cloud-practitioner.json");
      return m.default as unknown as ExamData;
    }
    case "ai-practitioner": {
      const m = await import("../data/ai-practitioner.json");
      return m.default as unknown as ExamData;
    }
  }
}
