import type { ExamData, ExamId, Provider } from "../types";
import metaJson from "../data/meta.json";

export interface ExamMeta {
  examId: ExamId;
  examName: string;
  examShort: string;
  questionCount: number;
  provider: Provider;
}

// meta.json is regenerated by scripts/parse-questions.mjs alongside the per-exam
// question files. It's small enough to ship in the main bundle so the setup
// screen can show counts without pulling the full question arrays.
export const examMeta: Record<ExamId, ExamMeta> = metaJson as Record<ExamId, ExamMeta>;

// Explicit per-provider ordering — meta.json key order isn't a contract worth
// depending on for display order.
const PROVIDER_EXAM_IDS: Record<Provider, ExamId[]> = {
  aws: ["ai-practitioner", "cloud-practitioner"],
  claude: ["associate-foundations", "developer-foundations"],
};

export function examsForProvider(provider: Provider): ExamMeta[] {
  return PROVIDER_EXAM_IDS[provider]
    .filter((id) => Object.prototype.hasOwnProperty.call(examMeta, id))
    .map((id) => examMeta[id]);
}

// Lazy-loaded — Vite splits each JSON into its own chunk so users only download
// the question set they actually start.
export async function loadExam(id: ExamId): Promise<ExamData> {
  switch (id) {
    case "cloud-practitioner": {
      const m = await import("../data/aws/cloud-practitioner.json");
      return m.default as unknown as ExamData;
    }
    case "ai-practitioner": {
      const m = await import("../data/aws/ai-practitioner.json");
      return m.default as unknown as ExamData;
    }
    case "developer-foundations": {
      const m = await import("../data/claude/developer-foundations.json");
      return m.default as unknown as ExamData;
    }
    case "associate-foundations": {
      const m = await import("../data/claude/associate-foundations.json");
      return m.default as unknown as ExamData;
    }
  }
}
